### ISSUE TITLE
@mix doesn't work with module qualified macros

### ISSUE THREAD

**Issue by bgroenks96** [rafaqz/Mixers.jl#9]
MWE:

```julia
using Mixers

@mix Base.@kwdef struct Foo
    bar = 1
end
```
fails with error:

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Expr to an object of type Symbol
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:205
  Symbol(::Any...) at strings/basic.jl:229
Stacktrace:
  [1] push!(a::Vector{Symbol}, item::Expr)
    @ Base ./array.jl:932
  [2] chained_macros!(macros::Vector{Symbol}, ex::Expr)
    @ Mixers ~/.julia/packages/Mixers/f3AVv/src/Mixers.jl:87
  [3] chained_macros
    @ ~/.julia/packages/Mixers/f3AVv/src/Mixers.jl:83 [inlined]
  [4] defmacro(ex::Expr, prepend::Bool)
    @ Mixers ~/.julia/packages/Mixers/f3AVv/src/Mixers.jl:37
  [5] var"@mix"(__source__::LineNumberNode, __module__::Module, ex::Any)
    @ Mixers ~/.julia/packages/Mixers/f3AVv/src/Mixers.jl:24
  [6] eval
    @ ./boot.jl:360 [inlined]
  [7] eval
    @ ./Base.jl:39 [inlined]
  [8] repleval(m::Module, code::Expr, #unused#::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.5.11/scripts/packages/VSCodeServer/src/repl.jl:157
  [9] (::VSCodeServer.var"#69#71"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.5.11/scripts/packages/VSCodeServer/src/repl.jl:123
 [10] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:491
 [11] with_logger
    @ ./logging.jl:603 [inlined]
 [12] (::VSCodeServer.var"#68#70"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.5.11/scripts/packages/VSCodeServer/src/repl.jl:124
 [13] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [14] invokelatest(::Any)
    @ Base ./essentials.jl:706
 [15] macro expansion
    @ ~/.vscode/extensions/julialang.language-julia-1.5.11/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
 [16] (::VSCodeServer.var"#53#54")()
    @ VSCodeServer ./task.jl:411
in expression starting at REPL[10]:1
```

but

```julia
using Mixers
using Base: @kwdef

@mix @kwdef struct Foo
    bar = 1
end
```
works fine.

Mixers v0.1.1 on:
```
julia> versioninfo()
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by rafaqz** [comment]
Interesting, maybe an escaping issue? PR would be merged! But I dont actually use this anymore, its mostly a bad idea ;)

**Comment by bgroenks96** [comment]
I was going to use it and then decided against it haha.

I am curious why you think it's a bad idea, though? Mixins are a fairly common programming pattern.

**Comment by rafaqz** [comment]
Yeah I thought so too when I wrote this. But it makes refactoring harder in the long term. Its very hard for collaborators to understand, and if you just use composition from the start refactors are more obvious. Using `@mix` they aren't. 

Basically you lose some of the strength of types + multiple dispatch by collecting things in this macro instead of a regular object.

In practice I have refactored to using composition 100% of the time I used the macro, so now I just start out like that.

**Comment by hhaensel** [comment]
This was actually solved by #10 .

@rafaqz 
Maybe I am missing something. Could you elaborate a bit on how you use composition? Maybe a short example how to achieve the same thing with composition and with `@mix`?

**Comment by rafaqz** [comment]
Composition can be defining a struct that has the same fields as what you would put in a mixin, then using this struct as a single field in the parent object.

The downside is the fields are nested. The upside is you have an object to reuse, dispatch on and pass around, and no macros.

**Comment by hhaensel** [comment]
Understood, I thought that's what you mean. - Thanks for your quick response.

I plan to use it for the [definition of a model in Stipple.jl](https://github.com/GenieFramework/Stipple.jl/issues/118) that is synchronised via json.
In that case it makes sense to have the fields added to the model, as they will be synchronised separately. Otherwise the whole object will be resent via json, which produces lots of overhead - at least unless we realise element-wise updating of fields, which may be provided in the future.

**Comment by hhaensel** [comment]
So do we close this issue?

**Comment by rafaqz** [comment]
Yeab I was actually wondering if serialisation was your use-case. It does make sense to use mixins for that.
